apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: perftest
spec:
  source:
    git:
      uri: https://github.com/peterajessup/cphtestp
      ref: master
  output:
    to:
      kind: ImageStreamTag
      name: 'perftest:v0.01'
  strategy:
    dockerStrategy:
      pullSecret:
        name: ibm-entitlement-key
      dockerfilePath: .
