apiVersion: batch/v1 
kind: Job
metadata:
  labels:
    run: cphtestp
  name: cphtestp
  namespace: mq
spec:
  template:
    metadata:
      labels:
        run: cphtestp
    spec:
      containers:
      - env:
        - name: LICENSE
          value: accept
        - name: MQ_QMGR_HOSTNAME
          value: mq1-ibm-mq 
        - name: MQ_QMGR_PORT
          value: "1414"
        - name: MQ_USERID
          value: 
        - name: MQ_PASSWORD
          value: 
        - name: MQ_QMGR_CHANNEL
          value: ACE.CONN 
        - name: MQ_NON_PERSISTENT
          value: "0"
        - name: MQ_QMGR_NAME
          value: QM1 
        - name: MQ_DATA
          value: 
        - name: MQ_RESULTS_CSV
          value: "FALSE"
        - name: MQ_RESULTS
          value: "TRUE"
        - name: MQ_QMGR_QREQUEST_PREFIX 
          value: REQUEST 
        - name: MQ_QMGR_QREPLY_PREFIX 
          value: REPLY 
        - name: MQ_RESPONDER_THREADS
          value: "8" 
        image: image-registry.openshift-image-registry.svc:5000/mq/perftest:v0.01
#        imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        name: cphtestp
        resources: 
          requests:
            memory: "16Gi"
            cpu: "2"
          limits:
            memory: "16Gi"
            cpu: "4"
        terminationMessagePath: /dev/termination-log
        volumeMounts:
          - name: cphdata
            mountPath: /var/cph
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cphdata
        emptyDir: {}
